# Environment Settings for knowledge-aware recommendation models on Weixin_Sports
# CKE, KGAT, KGCN, KGNNLS, Firzen
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id
ENTITY_ID_FIELD: entity_id
load_col:
    inter: [user_id, item_id, splitting_label]
    kg: [head_id, relation_id, tail_id]
    link: [item_id, entity_id]
    useremb: [uid, user_emb]
    itememb: [iid, item_emb]
additional_feat_suffix: [useremb, itememb]

alias_of_user_id: [uid]
alias_of_item_id: [iid]

preload_weight:
    uid: user_emb
    iid: item_emb

# model config
embedding_size: 64
kg_embedding_size: 64
reg_weights: [1e-02,1e-02]

# Training and evaluation config
eval_args:
  split: {'COLD':[0.8,0.1,0.1]}
  order: RO
  group_by: user
  mode: full #uni99 #full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 20
valid_metric: MRR@20

eval_handc: True #False
log_wandb: True

# filtering
user_inter_num_interval: "[5,inf)"
#item_inter_num_interval: "[5,inf)"

gpu_id: '3'

save_dataset: True

train_neg_sample_args:
    sample_by: user

wandb_project: 'ColdStartItem_Tencent'

# multi-modal features
vision_feature_file: image_feat.npy
text_feature_file: text_feat.npy
mm_feature_file: mm_feat.npy

# pretrain settings
user_pretrain: True
item_pretrain: True
pretrain_update: True

